# Generated by Django 4.2.16 on 2024-10-03 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0002_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assethistory',
            name='asset_name',
        ),
        migrations.RemoveField(
            model_name='assethistory',
            name='user',
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_name', models.CharField(max_length=100)),
                ('interval', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_app.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='assethistory',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='trading_app.dataset'),
        ),
    ]
