# Generated by Django 4.2.16 on 2024-10-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0004_alter_assethistory_dataset_trainingsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedmodel',
            name='training_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_app.trainingsession'),
        ),
    ]
