# Generated by Django 4.2.16 on 2024-10-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0005_alter_trainedmodel_training_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='mae',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='mse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='rmse',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
