# Generated by Django 4.2.16 on 2024-10-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0006_trainingsession_mae_trainingsession_mse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
