# Generated by Django 4.2.16 on 2024-10-09 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0007_trainingsession_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
