# Generated by Django 4.1.13 on 2024-10-09 16:21

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0008_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainedmodel',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='trainedmodel',
            name='model_file',
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='model_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='history',
            field=JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='indicators',
            field=JSONField(default=list),
        ),
        migrations.AlterModelTable(
            name='trainedmodel',
            table='trained_model',
        ),
        migrations.CreateModel(
            name='TradeSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('trade_type', models.CharField(choices=[('LONG OPEN', 'LONG OPEN'), ('LONG CLOSE', 'LONG CLOSE'), ('SHORT OPEN', 'SHORT OPEN'), ('SHORT CLOSE', 'SHORT CLOSE'), ('STOP LOSS', 'STOP LOSS')], max_length=20)),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('stop_loss_reached', models.BooleanField(default=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='trading_app.trainedmodel')),
            ],
        ),
    ]
