# Generated by Django 4.1.13 on 2024-10-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0009_alter_trainedmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainedmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='trainedmodel',
            name='model_data',
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='model_data_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='indicators',
            field=models.JSONField(default=list),
        ),
        migrations.AlterModelTable(
            name='trainedmodel',
            table=None,
        ),
    ]
