# Generated by Django 4.1.13 on 2024-10-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0010_alter_trainedmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesignal',
            name='trade_type',
            field=models.CharField(choices=[('LONG OPEN', 'LONG OPEN'), ('LONG CLOSE', 'LONG CLOSE'), ('SHORT OPEN', 'SHORT OPEN'), ('SHORT CLOSE', 'SHORT CLOSE'), ('HOLD', 'HOLD'), ('EXIT', 'EXIT'), ('STOP LOSS', 'STOP LOSS')], max_length=20),
        ),
    ]
